name: CSV Issue
description: Download Issue
title: "[CSV ISSUE] <title>"
labels: ["CSV Issue"]
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: Explain
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: Explain
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false
- 
