name: Test Issue 
on:
  issues:
    types:
    - opened

    jobs:
      test-job:
        runs-on: ubuntu-latest

        steps:
        -name: Print Issue Detected
        run: echo "New Issue Detected"
    
 
